version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - "wp-db:/var/lib/postgresql/data"

  mnist_service:
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    build: ./mnist_service
    ports:
      - 8000:8000
    volumes:
      - be-files:/files
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_SERVICE=${DB_SERVICE}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - FLASK_APP=${FLASK_APP}

volumes:
  wp-db:
  be-files:
